---
- name: Deploy Valheim Containers
  hosts: all
  become: true
  tasks:
    - name: Install Docker Compose
      apt:
        name: docker-compose
        state: present
      become: true

    - name: Run Docker Compose
      docker_compose:
        project_src: ./
        state: present

    - name: Open ports for Valheim Milan
      shell: "ufw allow 3456:3457/udp comment 'Valheim-Milan'"

    - name: Open ports for Valheim Kids
      shell: "ufw allow 3458:3459/udp comment 'Valheim-Kids'"

